version: '3'

services:

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5434:5432

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042" # native protocol clients